### ISSUE TITLE
Replacing `shell=True`

### ISSUE THREAD

**Issue by MattPinder** [topel-research-group/Bamboozle#11]
Using `shell=True` can [constitute a security risk](https://docs.python.org/3.7/library/subprocess.html#security-considerations), so I've been trying to fix these issues where possible (e.g. by switching from `%s` substitutions to lists when specifying commands).
Where commands are more complicated, such as those involving pipes, these will require a bit of extra planning to fix, though [something like this](https://security.openstack.org/guidelines/dg_avoid-shell-true.html) may be the approach we need.

**Comment by GeoMicroSoares** [comment]
Sorted in this [commit](https://github.com/topel-research-group/Bamboozle/commit/fcd9d347b57bccd53e3c3b71d010c259779edcd8)! :)

**Comment by GeoMicroSoares** [comment]
Actually solved and tested now.
