### ISSUE TITLE
snoeffdb

### ISSUE THREAD

**Issue by mtop** [topel-research-group/Bamboozle#4]
Add a specific option for defining the snpEff database to use. Something like this might work:

```
parser.add_argument("--snpeffdb", \
                        nargs=1, \
                        help="PATH to the snpeff database to use")
```

**Comment by GeoMicroSoares** [comment]
Added to `bamboozle.py` in `andre_sv` [here](https://github.com/topel-research-group/Bamboozle/commit/6511cb3257dfb1b1c4f821fe251e0e40bf2b08ba).
